[package]
name = "ZitMail"
version = "0.0.1"
edition = "2024"
authors = ["KirsminX"]
license = "MIT"
publish = false

[dependencies]
toml = "0.9.4"
lazy_static = "1.5.0"
url = "2.5.4"
chrono = { version = "0.4.41", features = ["serde"] }
chrono-tz = "0.10.4"
crossbeam-channel = "0.5.15"
